[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Networks = "027a387e-e55f-4537-a155-5037e5a23bdb"
NetworkDynamic = "2ec8e4a1-edb9-4657-8cef-4d333c164b0b"
SNA = "199dfc94-006f-42e6-80fa-49ca4fc5f549"
TSNA = "d87fbcfe-12dd-4101-bd65-651c391eab70"

[sources]
TSNA = {path = ".."}
Networks = {path = "../../Networks.jl"}
NetworkDynamic = {path = "../../NetworkDynamic.jl"}
SNA = {path = "../../SNA.jl"}

[compat]
Documenter = "1"
